2022-11-20 21:31:17|INFO|   This is a file logger   |file_logger test_app.py:test_app:22, 24276, 17804, MainThread, MainProcess|
2022-11-20 21:31:17|WARNING|   This is a file logger   |file_logger test_app.py:test_app:24, 24276, 17804, MainThread, MainProcess|
2022-11-20 21:31:17|ERROR|   This is a file logger   |file_logger test_app.py:test_app:25, 24276, 17804, MainThread, MainProcess|
2022-11-20 21:31:17|DEBUG|   This is a file logger   |file_logger test_app.py:test_app:26, 24276, 17804, MainThread, MainProcess|
2022-11-20 21:31:17|CRITICAL|   This is a file logger   |file_logger test_app.py:test_app:27, 24276, 17804, MainThread, MainProcess|
2022-11-20 21:31:17|ERROR|   This is a test   |file_logger test_app.py:test_app:32, 24276, 17804, MainThread, MainProcess|
Traceback (most recent call last):
  File "g:\_Manono_USER\Manono\Desktop\git\custom_logger_python\test_app.py", line 30, in test_app
    raise Exception("This is a test")
Exception: This is a test
2022-11-20 21:47:34|INFO|   This is a file logger   |file_logger test_app.py:test_app:22, 24608, 29936, MainThread, MainProcess|
2022-11-20 21:47:34|WARNING|   This is a file logger   |file_logger test_app.py:test_app:24, 24608, 29936, MainThread, MainProcess|
2022-11-20 21:47:34|ERROR|   This is a file logger   |file_logger test_app.py:test_app:25, 24608, 29936, MainThread, MainProcess|
2022-11-20 21:47:34|DEBUG|   This is a file logger   |file_logger test_app.py:test_app:26, 24608, 29936, MainThread, MainProcess|
2022-11-20 21:47:34|CRITICAL|   This is a file logger   |file_logger test_app.py:test_app:27, 24608, 29936, MainThread, MainProcess|
2022-11-20 21:47:34|ERROR|   This is a test   |file_logger test_app.py:test_app:32, 24608, 29936, MainThread, MainProcess|
Traceback (most recent call last):
  File "g:\_Manono_USER\Manono\Desktop\git\custom_logger_python\test_app.py", line 30, in test_app
    raise Exception("This is a test")
Exception: This is a test
2022-11-20 21:53:16|INFO|   This is a file logger   |file_logger test_app.py:test_app:22, 25900, 29724, MainThread, MainProcess|
2022-11-20 21:53:16|WARNING|   This is a file logger   |file_logger test_app.py:test_app:24, 25900, 29724, MainThread, MainProcess|
2022-11-20 21:53:16|ERROR|   This is a file logger   |file_logger test_app.py:test_app:25, 25900, 29724, MainThread, MainProcess|
2022-11-20 21:53:16|DEBUG|   This is a file logger   |file_logger test_app.py:test_app:26, 25900, 29724, MainThread, MainProcess|
2022-11-20 21:53:16|CRITICAL|   This is a file logger   |file_logger test_app.py:test_app:27, 25900, 29724, MainThread, MainProcess|
2022-11-20 21:53:16|ERROR|   This is a test   |file_logger test_app.py:test_app:32, 25900, 29724, MainThread, MainProcess|
Traceback (most recent call last):
  File "g:\_Manono_USER\Manono\Desktop\git\custom_logger_python\test_app.py", line 30, in test_app
    raise Exception("This is a test")
Exception: This is a test
